Update compile-db-objects.yml
v3.5

diff --git a/.github/workflows/compile-db-objects.yml b/.github/workflows/compile-db-objects.yml
--- a/.github/workflows/compile-db-objects.yml
+++ b/.github/workflows/compile-db-objects.yml
@@ -37,22 +37,22 @@ jobs:
         set -euo pipefail
     
         # Check if the 'before' commit exists
-        #  if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
-        #   echo "No previous commit to compare. First commit detected."
-        #  exit 0
-        # fi    
-        #  if ! git cat-file -e "${{ github.event.before }}^{commit}"; then
-        #    echo "Previous commit not found. It might have been force-pushed or deleted."
-        #    exit 0
-        #  fi    
+        ##  if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
+        ##   echo "No previous commit to compare. First commit detected."
+        ##  exit 0
+        ## fi    
+        ##  if ! git cat-file -e "${{ github.event.before }}^{commit}"; then
+        ##    echo "Previous commit not found. It might have been force-pushed or deleted."
+        ##    exit 0
+        ##  fi    
 
         # Get the list of changed files
-        # FILES=$(git show --name-only $COMMIT_HASH --pretty=format:)
-        # Check if any files were found
-        # if [ -z "$FILES" ]; then
-        #  echo "No files were changed. Exiting."
-        #  exit 0
-        # fi
+        ## FILES=$(git show --name-only $COMMIT_HASH --pretty=format:)
+        ## Check if any files were found
+        ## if [ -z "$FILES" ]; then
+        ##  echo "No files were changed. Exiting."
+        ##  exit 0
+        ## fi
     
         # Export the list of files as an environment variable
         # echo "FILES=$FILES" # >> $GITHUB_ENV 
@@ -64,7 +64,8 @@ jobs:
         echo "COMMIT_HASH is ${{ env.COMMIT_HASH }}"
 
         # Get Changed Files      
-        FILES=$(git show --name-only ${{ env.COMMIT_HASH }} --pretty=format:)
+        ## FILES=$(git show --name-only ${{ env.COMMIT_HASH }} --pretty=format:)
+        FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.event.before }} ${{ github.sha }})
         echo "FILES=$FILES" # >> $GITHUB_ENV
         
         # Debug Changed Files
