Update compile-db-objects.yml
v2.0

diff --git a/.github/workflows/compile-db-objects.yml b/.github/workflows/compile-db-objects.yml
--- a/.github/workflows/compile-db-objects.yml
+++ b/.github/workflows/compile-db-objects.yml
@@ -3,7 +3,7 @@ name: Compile Changed Oracle Database Objects with Logs and Environments
 on:
   push:
     branches:
-      - mainer
+      - main
 
 jobs:
   compile-changed-objects:
@@ -30,9 +30,17 @@ jobs:
     - name: Get Changed Files
       id: changes
       run: |
-        #echo "FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.event.before }} ${{ github.sha }})" >> $GITHUB_ENV
-        FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }}) 
-        echo "FILES=$FILES" >> $GITHUB_ENV
+        # Get the list of changed files
+        FILES=$(git diff --name-only "${{ github.event.before }}" "${{ github.sha }}")
+        
+        # Handle errors if no files are found or the git diff command fails
+        if [ $? -ne 0 ] || [ -z "$FILES" ]; then
+          echo "Error: Unable to determine changed files or no files were changed."
+          exit 1
+        fi
+
+        # Export the list of files as an environment variable
+        echo "FILES=$FILES" >> $GITHUB_ENV    
 
     # Step 3: Environment-Based Segregation
     - name: Set Environment Variables
